name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'backend/**'
      - 'cloudbuild.yaml'
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: backend-production  # Use separate environment for backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy Backend to Cloud Run
      run: |
        # Deploy directly from source (no Docker registry needed)
        # Using the existing service name from your current deployment
        gcloud run deploy xement-ai-backend \
          --source ./backend \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --port 8000 \
          --memory 1Gi \
          --cpu 1 \
          --max-instances 10 \
          --project=${{ secrets.GCP_PROJECT_ID }}

    - name: Verify deployment
      run: |
        echo "Backend deployed successfully!"
